apiVersion: v1
kind: Service
metadata:
  name: flask-node-service
spec:
  type: NodePort
  selector:
    app: flasknode
  ports:
  - port: 80
    targetPort: 7777
    nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasknode
  template:
    metadata:
      labels:
        app: flasknode
    spec:
      containers:
      - name: flasknode
        image: icr.io/flask-node/personal-expense-tracker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7777
