apiVersion: v1
kind: Service
metadata:
  name: personal-expense-tracker
spec:
  selector:
    app: personal-expense-tracker
  ports:
  - port: 7777
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-expense-tracker
  labels:
    app: personal-expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-expense-tracker
  template:
    metadata:
      labels:
        app: personal-expense-tracker
    spec:
      containers:
      - name: personal-expense-tracker
        image: icr.io/flask-node/personal-expense-tracker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7777
